apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubenetes
  region: us-east-1

iam:
#   withOIDC: true
  serviceRoleARN: arn:aws:iam::936896248725:role/eks-power-role

nodeGroups:
  - name: capstone
    instanceType: t2.small
    amiFamily: AmazonLinux2
    # desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacity